name: On-push to LatestRelease, update Development branch

on:
  push:
    branches:
      - LatestRelease

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git configuration
        run: |
          git config --global user.email "lars@beksoft.dk"
          git config --global user.name "Lars M Bek (automated)"

      - name: Checkout LatestRelease
        uses: actions/checkout@v2
        with:
          ref: LatestRelease

      - name: Checkout Development
        uses: actions/checkout@v2
        with:
          ref: Development

      - name: Merge LatestRelease into Development branch
        run: |
          git merge --no-commit origin/LatestRelease # The source branch to merge from
          git commit -C HEAD --amend # Amend the previous commit with the merge changes
          git push # Push the changes to the remote repository
