name: On-push to LatestRelease, merge LatestRelease into Development Branch

on:
  push:
    branches:
      - LatestRelease

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git user
        run: |
          git config --global user.name "Lars M Bek (automated)"
          git config --global user.email "lars@beksoft.dk"

      - name: Checkout LatestRelease
        uses: actions/checkout@v2
        with:
          ref: LatestRelease

      - name: Checkout Development
        uses: actions/checkout@v2
        with:
          ref: Development

      - name: Merge LatestRelease into Development branch
        run: |
          git merge --allow-unrelated-histories origin/LatestRelease --no-edit
          git push origin Development
