name: Update every branch with merge from LatestRelease

on:
  push:
    branches:
      - LatestRelease

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout LatestRelease
      uses: actions/checkout@v2
      with:
        ref: LatestRelease

    - name: Get list of branches
      run: |
        git branch -r | grep -v LatestRelease | awk '{print $1}' > branches.txt

    - name: Merge LatestRelease into all branches
      run: |
        while read branch; do
          git checkout $branch
          git merge LatestRelease --no-edit
          git push origin $branch
        done < branches.txt
