# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Tests (Linux)

on:
 # push:
 #   branches: [ "Development" ]
  pull_request:
    branches: [ "Development", "LatestRelease" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    #- uses: browser-actions/setup-chrome@v1
    #- run: chrome --version

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Go Tests
      run: go test -v ./tests/...
    
#    - name: Go Tests utils
#      run: go test -v ./tests/utils
      
    #- name: Go Tests net
    #  run: go test -v ./tests/utils/net
