name: Update Development branch with merge from LatestRelease

on:
  push:
    branches:
      - LatestRelease

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout LatestRelease
      uses: actions/checkout@v2
      with:
        ref: LatestRelease

    - name: Merge LatestRelease into Development branch
      run: |
        git checkout Development
        git merge LatestRelease --no-edit
        git push origin Development
