name: On Push to LatestRelease, merge LatestRelease into Development Branch

on:
  push:
    branches:
      - LatestRelease

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout LatestRelease
      uses: actions/checkout@v2
      with:
        ref: LatestRelease

    - name: Checkout Development
      uses: actions/checkout@v2
      with:
        ref: Development

    - name: Merge LatestRelease into Development
      run: |
        git merge LatestRelease --no-edit
        git push origin Development
